#!/usr/bin/env bash
set -euo pipefail

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# setup-caddy.sh — HTTPS dev proxy with wildcard certs
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#
# Architecture:
#   Client (ceres) ──HTTPS──▷ Caddy :443 ──HTTP──▷ Portless :8080 ──▷ App
#
#   Caddy:     TLS termination with Let's Encrypt wildcard certs
#              via Cloudflare DNS-01 challenge. Rewrites Host header
#              from foo.{hostname}.webfront.app → foo.{hostname}
#   Portless:  Subdomain→app routing (TLD = hostname).
#              Manages dev server lifecycle and port assignment.
#
# This script is idempotent — safe to re-run on an already-configured machine.
# Derives the domain from the machine's hostname automatically:
#   pluto  → *.pluto.webfront.app
#   ceres  → *.ceres.webfront.app
#
# What it does:
#   1. Installs Caddy (apt) with the Cloudflare DNS plugin
#   2. Writes /etc/caddy/Caddyfile for *.{hostname}.webfront.app
#   3. Stores CF_API_Token in /etc/caddy/env (mode 600, owned by caddy)
#   4. Creates a systemd override so Caddy reads the env file
#   5. Creates a portless-proxy.service (user-mode, port 8080, no TLS)
#   6. Enables + starts both services (persist across reboot)
#   7. Verifies TLS and prints next steps
#
# Prerequisites (before running this script on a new server):
#   1. Set the machine's hostname (hostnamectl set-hostname <name>)
#   2. Source CF_API_Token:  source zsh/env.d/91_cloudflare_secrets.zsh
#   3. Install portless:    mise use -g npm:portless
#   4. Create Cloudflare DNS records (see "Next steps" output below)
#
# Cloudflare DNS records needed (per machine):
#   A    {hostname}.webfront.app       → machine's LAN IP (e.g. 192.168.0.96)
#   A    *.{hostname}.webfront.app     → machine's LAN IP (same)
#
# CF_API_Token needs Zone:DNS:Edit permission for the webfront.app zone.
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

HOSTNAME=$(hostname)
DOMAIN="${HOSTNAME}.webfront.app"

# ── Preflight checks ─────────────────────────────────────────────────
if [[ -z "${CF_API_Token:-}" ]]; then
  echo "ERROR: CF_API_Token not set. Source zsh/env.d/91_cloudflare_secrets.zsh first."
  exit 1
fi

if ! command -v portless &>/dev/null; then
  echo "ERROR: portless not found. Install with: mise use -g npm:portless"
  exit 1
fi

# Check if something other than Caddy is already holding port 443
port_holder=$(sudo ss -tlnp 'sport = :443' 2>/dev/null | tail -n +2 || true)
if [[ -n "$port_holder" ]]; then
  holder_pid=$(echo "$port_holder" | grep -oP 'pid=\K[0-9]+' | head -1)
  if [[ -n "$holder_pid" ]]; then
    holder_cmd=$(ps -p "$holder_pid" -o args= 2>/dev/null || echo "unknown")
    if [[ "$holder_cmd" != *caddy* ]]; then
      echo "ERROR: Port 443 is already in use by PID $holder_pid:"
      echo "  $holder_cmd"
      echo ""
      echo "Kill it first:  sudo kill $holder_pid"
      exit 1
    fi
  fi
fi

PORTLESS_BIN=$(command -v portless)
echo "Machine:   $HOSTNAME"
echo "Domain:    *.$DOMAIN"
echo "Portless:  $PORTLESS_BIN"
echo ""

# ── Install Caddy ────────────────────────────────────────────────────
install_caddy() {
  if command -v caddy &>/dev/null; then
    echo "Caddy already installed: $(caddy version)"
  else
    echo "Installing Caddy..."
    sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https curl

    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
      | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg

    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
      | sudo tee /etc/apt/sources.list.d/caddy-stable.list

    sudo apt update
    sudo apt install -y caddy
  fi

  # Ensure Cloudflare DNS plugin is installed
  if caddy list-modules 2>/dev/null | grep -q 'dns.providers.cloudflare'; then
    echo "Cloudflare DNS plugin already installed."
  else
    echo "Adding Cloudflare DNS plugin..."
    sudo caddy add-package github.com/caddy-dns/cloudflare
  fi
}

# ── Caddyfile ─────────────────────────────────────────────────────────
write_caddyfile() {
  echo "Writing /etc/caddy/Caddyfile for $DOMAIN..."
  sudo tee /etc/caddy/Caddyfile > /dev/null <<EOF
# Auto-generated by setup-caddy.sh for $HOSTNAME
# TLS termination for *.$DOMAIN via Cloudflare DNS-01 challenge
# Proxies to portless on localhost:8080, rewriting Host to match portless TLD

*.$DOMAIN {
	tls {
		dns cloudflare {env.CF_API_TOKEN}
	}

	# Rewrite Host: foo.$DOMAIN → foo.$HOSTNAME (portless TLD = hostname)
	reverse_proxy localhost:8080 {
		header_up Host {http.request.host.labels.3}.$HOSTNAME
	}
}

$DOMAIN {
	tls {
		dns cloudflare {env.CF_API_TOKEN}
	}

	respond "$HOSTNAME dev server" 200
}
EOF
}

# ── Caddy systemd environment ────────────────────────────────────────
setup_caddy_systemd() {
  echo "Configuring Caddy systemd service..."

  # Environment file with CF token
  sudo tee /etc/caddy/env > /dev/null <<EOF
CF_API_TOKEN=${CF_API_Token}
EOF
  sudo chmod 600 /etc/caddy/env
  sudo chown caddy:caddy /etc/caddy/env

  # Systemd override to load env file
  sudo mkdir -p /etc/systemd/system/caddy.service.d
  sudo tee /etc/systemd/system/caddy.service.d/override.conf > /dev/null <<EOF
[Service]
EnvironmentFile=/etc/caddy/env
EOF

  sudo systemctl daemon-reload
  sudo systemctl enable caddy
  sudo systemctl restart caddy
  echo "Caddy started."
}

# ── Portless systemd service ─────────────────────────────────────────
setup_portless_systemd() {
  echo "Creating portless-proxy systemd service..."

  # Stop any running portless proxy and clear stale state
  portless proxy stop -p 8080 2>/dev/null || true
  rm -f "$HOME/.portless/proxy.tld" "$HOME/.portless/proxy.pid" \
        "$HOME/.portless/proxy.port" "$HOME/.portless/proxy.lan"

  local mise_shims="$HOME/.local/share/mise/shims"

  sudo tee /etc/systemd/system/portless-proxy.service > /dev/null <<EOF
[Unit]
Description=Portless HTTP proxy for $DOMAIN
After=network.target

[Service]
Type=simple
User=$USER
Environment=HOME=$HOME
Environment=PATH=$mise_shims:/usr/local/bin:/usr/bin:/bin
Environment=PORTLESS_LAN=0
ExecStart=$mise_shims/portless proxy start --foreground --no-tls --tld $HOSTNAME -p 8080
Restart=on-failure
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF

  sudo systemctl daemon-reload
  sudo systemctl enable portless-proxy
  sudo systemctl restart portless-proxy
  echo "Portless proxy started on port 8080 (TLD: $HOSTNAME)."
}

# ── Verify ────────────────────────────────────────────────────────────
verify() {
  echo ""
  echo "Verifying setup..."
  sleep 2

  # Check Caddy
  if sudo systemctl is-active --quiet caddy; then
    echo "  ✓ Caddy is running"
  else
    echo "  ✗ Caddy failed to start"
    sudo journalctl -u caddy --no-pager -n 10
    return 1
  fi

  # Check portless
  if sudo systemctl is-active --quiet portless-proxy; then
    echo "  ✓ Portless proxy is running"
  else
    echo "  ✗ Portless proxy failed to start"
    sudo journalctl -u portless-proxy --no-pager -n 10
    return 1
  fi

  # Check TLS cert
  if curl -s -o /dev/null -w "%{http_code}" "https://$DOMAIN" 2>/dev/null | grep -q 200; then
    echo "  ✓ https://$DOMAIN responds with valid TLS"
  else
    echo "  … https://$DOMAIN not yet responding (cert may still be issuing)"
  fi

  local LAN_IP
  LAN_IP=$(hostname -I | awk '{print $1}')

  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo " Setup complete for $DOMAIN"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""
  echo "Services:"
  echo "  Caddy:      sudo systemctl status caddy"
  echo "  Portless:   sudo systemctl status portless-proxy"
  echo "  Caddy logs: sudo journalctl -u caddy -f"
  echo "  PL logs:    sudo journalctl -u portless-proxy -f"
  echo ""
  echo "Usage:"
  echo "  portless myapp pnpm dev  →  https://myapp.$DOMAIN"
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo " Next steps (if setting up a new server)"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""
  echo "1. Cloudflare DNS — add these A records for $DOMAIN:"
  echo "     $DOMAIN        → $LAN_IP"
  echo "     *.$DOMAIN      → $LAN_IP"
  echo ""
  echo "2. Access from other machines — no client config needed."
  echo "   Certs are real Let's Encrypt, trusted by all browsers/curl."
  echo ""
  echo "3. Firewall — ensure ports 443 and 80 are open on this machine."
  echo ""
  echo "4. Re-run this script any time — it is idempotent."
  echo ""
}

# ── Main ──────────────────────────────────────────────────────────────
install_caddy
write_caddyfile
setup_caddy_systemd
setup_portless_systemd
verify
