# Enable powerlevel10k prompt. The actual configuration lives in
# zsh/.p10k.zsh (1839 lines, generated by `p10k configure`) and is sourced
# from .zshrc after this file. The previous version of this file embedded a
# duplicate ~600-line config that was overwritten on every shell startup —
# 100% dead code.
source $ZDOTDIR/plugins/powerlevel10k/powerlevel10k.zsh-theme
